services:

  prometheus:
    image: prom/prometheus:v2.52.0
    container_name: prometheus
    environment:
      - TZ=America/Chicago # Change this to your timezone
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.size=5GB'
      - '--web.enable-lifecycle'
    restart: unless-stopped
    expose:
      - 9090
    networks:
      - monitoring
    extra_hosts:       
      - "host.docker.internal:host-gateway"

networks:
  monitoring:
    name: monitoring
    external: true

