---
###############################################################
#                         Users Database                      #
###############################################################

# This file can be used if you do not have an LDAP set up.

# List of users
users:
  user1:
    displayname: "Myuser"
    password: "passwd hash"
    email: myself@mydomain.com
    groups:
      - admins
      - dev
  user2:
    displayname: "ExampleUser"
    password: "passwd hash"
    email: themself@mydomain.com
    groups:
      - users
...
