---
###############################################################
#                         Users Database                      #
###############################################################

# This file can be used if you do not have an LDAP set up.

# List of users
users:
  adenmann:
    displayname: "Myuser"
    # Password is Authelia retwyw-tecSup-3jidjy
    password: "passwd hash"
    email: myself@mydomain.com
    groups:
      - admins
      - dev
  litamann:
    displayname: "ExampleUser"
    # Password is Authelia retwyw-tecSup-3jidjy
    password: "passwd hash"
    email: themself@mydomain.com
    groups:
      - users
...
