services: 
  chronograf:
    image: chronograf:latest
    ports:
      - '8888:8888'
    volumes:
      - chronograf-storage:/var/lib/chronograf
    depends_on:
      - influxdb
    env_file:
      - ./data/secrets.env
    networks:
      - monitoring
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.telegraf.entrypoints=http"
      - "traefik.http.routers.telegraf.rule=Host(`telegraf.mydomain.com`)"
      - "traefik.http.middlewares.telegraf-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.telegraf-secure.entrypoints=https"
      - "traefik.http.routers.telegraf-secure.rule=Host(`telegraf.mydomain.com`)"
      - "traefik.http.routers.telegraf-secure.tls=true"
      - "traefik.http.routers.telegraf-secure.service=telegraf"
      - "traefik.http.services.telegraf.loadbalancer.server.port=8888"
      - "traefik.docker.network=proxy"
      #- "traefik.http.routers.telegraf-secure.middlewares=authelia@docker"