services:
    influxdb:
    image: influxdb:1.8-alpine
    container_name: influxdb
    restart: always
    env_file:
      - ./data/secrets.env
    ports:
      - '8086:8086'  # Expose InfluxDB on port 8086
    volumes:
      - ./data:/var/lib/influxdb  # Mount the InfluxDB data directory
    networks:
      - monitoring  # Connect the InfluxDB container to the monitoring network
networks:
  monitoring:
    external: true  # Use an external network named 'monitoring'